/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leet_code.no003;

import org.junit.jupiter.params.*;
import org.junit.jupiter.params.provider.CsvSource;
import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.DisplayName;

class SolutionTest {

    private Solution solution = new Solution();

    @DisplayName("ExampleTest")
    @ParameterizedTest
    @CsvSource({
        "abcabcbb, 3",
        "bbbbb, 1",
        "pwwkew, 3", 
    })
    void exampleTest(String inputValue, int expect) {
        assertEquals(solution.lengthOfLongestSubstring(inputValue), expect);
    }

    @DisplayName("SubmitTest")
    @ParameterizedTest
    @CsvSource({
        "cdd, 2",
    })
    void submitTest(String inputValue, int expect) {
        assertEquals(solution.lengthOfLongestSubstring(inputValue), expect);
    }
}
